export enum CategoryEnum {
  ELETRONICOS = "ELETRONICOS" ,
  COMPUTADORES = "COMPUTADORES" ,
  AUDIO = "AUDIO" ,
  ACESSORIOS = "ACESSORIOS" ,
  FOTOGRAFIA = "FOTOGRAFIA" ,
  JOGOS = "JOGOS" ,
  SEGURANCA = "SEGURANCA"
}
