export enum CategoryEnum {
  ELETRONICOS = "ELETRÔNICOS",
  COMPUTADORES = "COMPUTADORES",
  AUDIO = "ÁUDIO",
  ACESSORIOS = "ACESSÓRIOS",
  FOTOGRAFIA = "FOTOGRAFIA",
  JOGOS = "JOGOS",
  SEGURANCA = "SEGURANÇA"
}
